profanities_list = ["Abelis",
    "Achujienas",
    "Alkasas",
    "Apipisti",
    "Apsisikti",
    "Atsipisti",
    "Babkes",
    "Barskintis",
    "bybys",
    "Bybi",
    "Blemba",
    "Blet",
    "Blin",
    "Bomzas",
    "Chronius",
    "Chujovas",
    "Debilas",
    "Drocinti",
    "Durnas",
    "Durnius",
    "Gandonas",
    "Homikas",
    "Ipisti",
    "Juodasiknis",
    "Kekse",
    "Krustis",
    "Kurva",
    "Kusys",
    "Lievas",
    "Lopas",
    "Myznius",
    "Myzti",
    "Nachui",
    "Nafig",
    "Nupisti",
    "Nusikti",
    "Nx",
    "Pedikas",
    "Persikti",
    "Pideras",
    "Pisti",
    "Pistis",
    "lochas",
    "Pyzd",
    "Pyzdinti",
    "Prapisti",
    "Prasikti",
    "Pravalas",
    "Psichas",
    "Pute",
    "Px",
    "Rura",
    "Rurinti",
    "Smaukalas",
    "Smaukyti",
    "Stopudovai",
    "Subine",
    "Subinkisys",
    "Subinlaizys",
    "Suknistas",
    "Supistas",
    "Supisti",
    "Susiktas",
    "Susikti",
    "Salava",
    "Savalka",
    "Sikna",
    "Siknaskyle",
    "Sikti",
    "Sizikas",
    "Sliundra",
    "Sudas",
    "Sudzius",
    "Uzpisti",
    "Zajabys",
    "Zalupa",
    "Zapadlo",
    "ZJB",
    "Zertva",
    "bybys",
    "Durnius",
    "Debilas",
    "Mulkis",
    "Smikis",
    "Vepla",
    "Pyderas",
    "Subinkisys",
    "Kurva",
    "Kekse",
    "Praskestuole",
    "Varvasnukis",
    "Subingalvis",
    "Kiausingalvis",
    "Nuopisa",
    "Nuosmauka",
    "Smaukalas",
    "Snarglius",
    "Myznius",
    "pydar",
    "pyder",
    "daunas",
    "latras",
    "Siknius",
    "Pislius",
    "Pirdzius",
    "Gaidys",
    "gaidziai",
    "zasinai",
    "Zasinas",
    "slekta",
    "asilai",
    "Asilas",
    "avinai",
    "Avinas",
    " sikna",
    " bybis",
    "Pydero",
    "nedakrustas",
    "Smaukyk",
    "Ciulpk",
    "bybi",
    "Sikau"
    "Nusiciulpk",
    "Issipisk",
    "sikna",
    "Apsisik",
    "Myzk"
    "Papisk"
    "Sik",
    "Ciulpk suda",
    "Myzk",
    "pyzdon",
    "arse bandit",
    "Arsehole",
    "ass boy",
    "ass",
    "asshole",
    "bastard",
    "bitch",
    "boner",
    "boob",
    "bugger",
    "bunghole",
    "cock",
    "cocksmoker",
    "cocksucker",
    "crap",
    "cum",
    "cunt",
    "dick",
    " shit",
    "faggot",
    "fart",
    "fuck",
    "fucker",
    "hooker",
    "jerk",
    "nigger",
    "piss",
    "screw",
    "shit",
    "shithead",
    "sissy",
    "slut",
    "snatch",
    "tits",
    "twat",
    "wanker",
    "Willie",
    " ciulporieznikas",
    " nuopisa",
    "gavnaedis",
    " duhovnas",
    "gaidziabybinishkas",
    "deshraweidis",
    "vaflius",
    " pedofilas",
    " deshrasiknis",
    " deshralupis",
    " pimpalas",
    "kiaushasnukis",
    " bybciulpys",
    "meshlawezys",
    " bybiaausis",
    " pyzdabolas",
    " bybiagalwis",
    " bybciulpys",
    "gaidziasnukis",
    " mockrusys",
    "bybiashiknis",
    " bybtraukys",
    " ishpistas nygerio",
    " usapautis",
    " shiknachiulpys",
    "kurwa",
    " naxui",
    " blet",
    " pisalas",
    " pisk",
    "papisk",
    "lohas",
    "bybishkis",
    " pirdaplioske",
    "shiknabudis",
    "apshiktaausis",
    " pedofilofynas",
    "kakashiknius",
    " kimshtaruris",
    " krushlys",
    "ishplerptaruris",
    " pituhas",
    "shiknatiltis",
    " dziundze",
    " kushintaakis",
    " naholewas",
    " masturbatoris",
    " putwarske",
    "siknawarys",
    "pyderzoidas",
    " kamasutra",
    "ciuriuriukas",
    "skystapautis",
    "lama ",
    "duhas ",
    "duchas ",
    "atmata  ",
    "nx  ",
    "nxj  ",
    "bl  ",
    "blt  ",
    "ble   ",
    "krw  ",
    "krv ",
    "px  ",
    "pochui  ",
    "jibanas  ",
    "sperma",
    "bibis",
    "bibys",
    "pedofil",
    "ringtone",
    "href",
    "sex",
    "seks",
    "porn",
    "enlarge",
    "penis",
    "jobanas "]

# strip spaces, and make lower-case
profanities_list = [s.strip().lower() for s in profanities_list]