#!/usr/bin/env python
# -*- coding: utf-8 -*-

MunicipalityCases = {
        u"Akmenė":u"Akmenės rajono savivaldybė",
        u"Alytus":u"Alytaus miesto savivaldybė",
        u"Alytaus":u"Alytaus rajono savivaldybė",
        u"Anykščiai":u"Anykščių rajono savivaldybė",
        u"Birštonas":u"Birštono savivaldybė",
        u"Biržai":u"Biržų rajono savivaldybė",
        u"Druskininkai":u"Druskininkų savivaldybė",
        u"Elektrėnai":u"Elektrėnų savivaldybė",
        u"Ignalina":u"Ignalinos rajono savivaldybė",
        u"Jonava":u"Jonavos rajono savivaldybė",
        u"Joniškis":u"Joniškio rajono savivaldybė",
        u"Jurbarkas":u"Jurbarko rajono savivaldybė",
        u"Kaišiadoriai":u"Kaišiadorių rajono savivaldybė",
        u"Kalvarija":u"Kalvarijos savivaldybė",
        u"Kaunas":u"Kauno miesto savivaldybė",
        u"Kauno":u"Kauno rajono savivaldybė",
        u"Kazlų Rūda":u"Kazlų Rūdos savivaldybė",
        u"Kelmė":u"Kelmės rajono savivaldybė",
        u"Klaipėda":u"Klaipėdos miesto savivaldybė",
        u"Klaipėdos":u"Klaipėdos rajono savivaldybė",
        u"Kretinga":u"Kretingos rajono savivaldybė",
        u"Kupiškis":u"Kupiškio rajono savivaldybė",
        u"Kėdainiau":u"Kėdainių rajono savivaldybė",
        u"Lazdijai":u"Lazdijų rajono savivaldybė",
        u"Marijampolė":u"Marijampolės savivaldybė",
        u"Mažeikiai":u"Mažeikių rajono savivaldybė",
        u"Molėtai":u"Molėtų rajono savivaldybė",
        u"Neringa":u"Neringos savivaldybė",
        u"Pagėgiai":u"Pagėgių savivaldybė",
        u"Pakruojis":u"Pakruojo rajono savivaldybė",
        u"Palanga":u"Palangos miesto savivaldybė",
        u"Panevėžys":u"Panevėžio miesto savivaldybė",
        u"Panevėžio":u"Panevėžio rajono savivaldybė",
        u"Pasvalys":u"Pasvalio rajono savivaldybė",
        u"Plungė":u"Plungės rajono savivaldybė",
        u"Prienai":u"Prienų rajono savivaldybė",
        u"Radviliškis":u"Radviliškio rajono savivaldybė",
        u"Raseiniai":u"Raseinių rajono savivaldybė",
        u"Rietavas":u"Rietavo savivaldybė",
        u"Rokiškis":u"Rokiškio rajono savivaldybė",
        u"Skuodas":u"Skuodo rajono savivaldybė",
        u"Tauragė":u"Tauragės rajono savivaldybė",
        u"Telšiai":u"Telšių rajono savivaldybė",
        u"Trakai":u"Trakų rajono savivaldybė",
        u"Ukmergė":u"Ukmergės rajono savivaldybė",
        u"Utena":u"Utenos rajono savivaldybė",
        u"Varėna":u"Varėnos rajono savivaldybė",
        u"Vilkaviškis":u"Vilkaviškio rajono savivaldybė",
        u"Vilnius":u"Vilniaus miesto savivaldybė",
        u"Vilniaus":u"Vilniaus rajono savivaldybė",
        u"Visaginas":u"Visagino savivaldybė",
        u"Zarasai":u"Zarasų rajono savivaldybė",
        u"Šakiai":u"Šakių rajono savivaldybė",
        u"Šalčininkai":u"Šalčininkų rajono savivaldybė",
        u"Šiauliai":u"Šiaulių miesto savivaldybė",
        u"Šiaulių":u"Šiaulių rajono savivaldybė",
        u"Šilalė":u"Šilalės rajono savivaldybė",
        u"Šilutė":u"Šilutės rajono savivaldybė",
        u"Širvintos":u"Širvintų rajono savivaldybė",
        u"Švenčionys":u"Švenčionių rajono savivaldybė"}